// Inter-city (SETC/TNSTC) route slugs — long-distance buses between cities.
// Only routes verified to return ≥3 results from the search API.
export const SEO_ROUTE_SLUGS = [
  'chennai-to-madurai',
  'chennai-to-coimbatore',
  'chennai-to-salem',
  'chennai-to-tirunelveli',
  'chennai-to-erode',
  'chennai-to-thanjavur',
  'chennai-to-kumbakonam',
  'chennai-to-nagercoil',
  'chennai-to-dindigul',
  'chennai-to-karaikudi',
  'chennai-to-vellore',
  'chennai-to-tiruppur',
  'chennai-to-hosur',
  'chennai-to-puducherry',
  'chennai-to-kanyakumari',
  'chennai-to-villupuram',
  'chennai-to-karur',
  'chennai-to-namakkal',
  'chennai-to-dharmapuri',
  'chennai-to-krishnagiri',
  'chennai-to-pollachi',
  'chennai-to-palani',
  'chennai-to-ooty',
  'chennai-to-kodaikanal',
  'chennai-to-tiruvannamalai',
  'chennai-to-cuddalore',
  'chennai-to-marthandam',
  'chennai-to-rasipuram',
  'chennai-to-attur',
  'madurai-to-chennai',
  'madurai-to-coimbatore',
  'madurai-to-salem',
  'madurai-to-tirunelveli',
  'madurai-to-erode',
  'madurai-to-thanjavur',
  'madurai-to-kumbakonam',
  'madurai-to-nagercoil',
  'madurai-to-dindigul',
  'madurai-to-karaikudi',
  'madurai-to-vellore',
  'madurai-to-tiruppur',
  'madurai-to-hosur',
  'madurai-to-puducherry',
  'madurai-to-kanyakumari',
  'madurai-to-villupuram',
  'madurai-to-karur',
  'madurai-to-namakkal',
  'madurai-to-dharmapuri',
  'madurai-to-pollachi',
  'madurai-to-palani',
  'madurai-to-ooty',
  'madurai-to-kodaikanal',
  'madurai-to-tiruvannamalai',
  'madurai-to-cuddalore',
  'madurai-to-marthandam',
  'madurai-to-tenkasi',
  'madurai-to-rasipuram',
  'madurai-to-attur',
  'coimbatore-to-chennai',
  'coimbatore-to-madurai',
  'coimbatore-to-salem',
  'coimbatore-to-tirunelveli',
  'coimbatore-to-erode',
  'coimbatore-to-bangalore',
  'coimbatore-to-thanjavur',
  'coimbatore-to-kumbakonam',
  'coimbatore-to-nagercoil',
  'coimbatore-to-dindigul',
  'coimbatore-to-karaikudi',
  'coimbatore-to-vellore',
  'coimbatore-to-puducherry',
  'coimbatore-to-kanyakumari',
  'coimbatore-to-villupuram',
  'coimbatore-to-karur',
  'coimbatore-to-namakkal',
  'coimbatore-to-dharmapuri',
  'coimbatore-to-krishnagiri',
  'coimbatore-to-pollachi',
  'coimbatore-to-palani',
  'coimbatore-to-ooty',
  'coimbatore-to-kodaikanal',
  'coimbatore-to-tiruvannamalai',
  'coimbatore-to-cuddalore',
  'coimbatore-to-marthandam',
  'coimbatore-to-tenkasi',
  'coimbatore-to-rasipuram',
  'salem-to-chennai',
  'salem-to-madurai',
  'salem-to-coimbatore',
  'salem-to-tirunelveli',
  'salem-to-erode',

  'salem-to-thanjavur',
  'salem-to-kumbakonam',
  'salem-to-nagercoil',
  'salem-to-dindigul',
  'salem-to-karaikudi',
  'salem-to-vellore',
  'salem-to-tiruppur',
  'salem-to-hosur',
  'salem-to-puducherry',
  'salem-to-villupuram',
  'salem-to-karur',
  'salem-to-namakkal',
  'salem-to-dharmapuri',
  'salem-to-krishnagiri',
  'salem-to-pollachi',
  'salem-to-palani',
  'salem-to-ooty',
  'salem-to-tiruvannamalai',
  'salem-to-cuddalore',
  'salem-to-marthandam',
  'salem-to-tenkasi',
  'salem-to-rasipuram',
  'salem-to-attur',
  'tirunelveli-to-chennai',
  'tirunelveli-to-madurai',
  'tirunelveli-to-coimbatore',
  'tirunelveli-to-salem',
  'tirunelveli-to-erode',
  'tirunelveli-to-bangalore',
  'tirunelveli-to-thanjavur',
  'tirunelveli-to-kumbakonam',
  'tirunelveli-to-nagercoil',
  'tirunelveli-to-dindigul',
  'tirunelveli-to-karaikudi',
  'tirunelveli-to-vellore',
  'tirunelveli-to-tiruppur',
  'tirunelveli-to-hosur',
  'tirunelveli-to-puducherry',
  'tirunelveli-to-kanyakumari',
  'tirunelveli-to-villupuram',
  'tirunelveli-to-karur',
  'tirunelveli-to-namakkal',
  'tirunelveli-to-dharmapuri',
  'tirunelveli-to-krishnagiri',
  'tirunelveli-to-pollachi',
  'tirunelveli-to-palani',
  'tirunelveli-to-ooty',
  'tirunelveli-to-kodaikanal',
  'tirunelveli-to-tiruvannamalai',
  'tirunelveli-to-cuddalore',
  'tirunelveli-to-marthandam',
  'tirunelveli-to-tenkasi',
  'tirunelveli-to-attur',
  'erode-to-chennai',
  'erode-to-madurai',
  'erode-to-coimbatore',
  'erode-to-salem',
  'erode-to-tirunelveli',
  'erode-to-bangalore',
  'erode-to-thanjavur',
  'erode-to-kumbakonam',
  'erode-to-nagercoil',
  'erode-to-dindigul',
  'erode-to-karaikudi',
  'erode-to-vellore',
  'erode-to-tiruppur',
  'erode-to-hosur',
  'erode-to-puducherry',
  'erode-to-villupuram',
  'erode-to-karur',
  'erode-to-namakkal',
  'erode-to-dharmapuri',
  'erode-to-krishnagiri',
  'erode-to-pollachi',
  'erode-to-palani',
  'erode-to-ooty',
  'erode-to-kodaikanal',
  'erode-to-tiruvannamalai',
  'erode-to-cuddalore',
  'erode-to-marthandam',
  'erode-to-tenkasi',
  'erode-to-rasipuram',
  'erode-to-attur',
  'bangalore-to-chennai',
  'bangalore-to-madurai',
  'bangalore-to-coimbatore',
  'bangalore-to-salem',
  'bangalore-to-tirunelveli',
  'bangalore-to-thanjavur',
  'bangalore-to-kumbakonam',
  'bangalore-to-karaikudi',
  'bangalore-to-puducherry',
  'bangalore-to-pollachi',
  'thanjavur-to-chennai',
  'thanjavur-to-madurai',
  'thanjavur-to-coimbatore',
  'thanjavur-to-salem',
  'thanjavur-to-erode',
  'thanjavur-to-kumbakonam',
  'thanjavur-to-nagercoil',
  'thanjavur-to-dindigul',
  'thanjavur-to-karaikudi',
  'thanjavur-to-vellore',
  'thanjavur-to-tiruppur',
  'thanjavur-to-hosur',
  'thanjavur-to-puducherry',
  'thanjavur-to-kanyakumari',
  'thanjavur-to-villupuram',
  'thanjavur-to-karur',
  'thanjavur-to-namakkal',
  'thanjavur-to-dharmapuri',
  'thanjavur-to-krishnagiri',
  'thanjavur-to-pollachi',
  'thanjavur-to-palani',
  'thanjavur-to-ooty',
  'thanjavur-to-kodaikanal',
  'thanjavur-to-tiruvannamalai',
  'thanjavur-to-cuddalore',
  'thanjavur-to-tenkasi',
  'thanjavur-to-attur',
  'kumbakonam-to-chennai',
  'kumbakonam-to-madurai',
  'kumbakonam-to-coimbatore',
  'kumbakonam-to-salem',
  'kumbakonam-to-tirunelveli',
  'kumbakonam-to-erode',
  'kumbakonam-to-thanjavur',
  'kumbakonam-to-nagercoil',
  'kumbakonam-to-dindigul',
  'kumbakonam-to-karaikudi',
  'kumbakonam-to-vellore',
  'kumbakonam-to-tiruppur',
  'kumbakonam-to-hosur',
  'kumbakonam-to-puducherry',
  'kumbakonam-to-kanyakumari',
  'kumbakonam-to-villupuram',
  'kumbakonam-to-karur',
  'kumbakonam-to-namakkal',
  'kumbakonam-to-dharmapuri',
  'kumbakonam-to-krishnagiri',
  'kumbakonam-to-pollachi',
  'kumbakonam-to-palani',
  'kumbakonam-to-ooty',
  'kumbakonam-to-kodaikanal',
  'kumbakonam-to-tiruvannamalai',
  'kumbakonam-to-cuddalore',
  'kumbakonam-to-marthandam',
  'kumbakonam-to-tenkasi',
  'kumbakonam-to-rasipuram',
  'kumbakonam-to-attur',
  'nagercoil-to-chennai',
  'nagercoil-to-madurai',
  'nagercoil-to-coimbatore',
  'nagercoil-to-salem',
  'nagercoil-to-tirunelveli',
  'nagercoil-to-erode',
  'nagercoil-to-thanjavur',
  'nagercoil-to-kumbakonam',
  'nagercoil-to-dindigul',
  'nagercoil-to-vellore',
  'nagercoil-to-tiruppur',
  'nagercoil-to-hosur',
  'nagercoil-to-puducherry',
  'nagercoil-to-kanyakumari',
  'nagercoil-to-villupuram',
  'nagercoil-to-karur',
  'nagercoil-to-dharmapuri',
  'nagercoil-to-krishnagiri',
  'nagercoil-to-pollachi',
  'nagercoil-to-palani',
  'nagercoil-to-ooty',
  'nagercoil-to-kodaikanal',
  'nagercoil-to-tiruvannamalai',
  'nagercoil-to-cuddalore',
  'nagercoil-to-marthandam',
  'nagercoil-to-tenkasi',
  'nagercoil-to-attur',
  'dindigul-to-chennai',
  'dindigul-to-madurai',
  'dindigul-to-coimbatore',
  'dindigul-to-salem',
  'dindigul-to-tirunelveli',
  'dindigul-to-erode',
  'dindigul-to-bangalore',
  'dindigul-to-thanjavur',
  'dindigul-to-kumbakonam',
  'dindigul-to-nagercoil',
  'dindigul-to-karaikudi',
  'dindigul-to-vellore',
  'dindigul-to-tiruppur',
  'dindigul-to-hosur',
  'dindigul-to-villupuram',
  'dindigul-to-karur',
  'dindigul-to-namakkal',
  'dindigul-to-pollachi',
  'dindigul-to-palani',
  'dindigul-to-ooty',
  'dindigul-to-kodaikanal',
  'dindigul-to-tiruvannamalai',
  'dindigul-to-cuddalore',
  'dindigul-to-marthandam',
  'dindigul-to-tenkasi',
  'dindigul-to-attur',
  'karaikudi-to-chennai',
  'karaikudi-to-madurai',
  'karaikudi-to-coimbatore',
  'karaikudi-to-salem',
  'karaikudi-to-tirunelveli',
  'karaikudi-to-erode',
  'karaikudi-to-bangalore',
  'karaikudi-to-thanjavur',
  'karaikudi-to-kumbakonam',
  'karaikudi-to-dindigul',
  'karaikudi-to-vellore',
  'karaikudi-to-tiruppur',
  'karaikudi-to-hosur',
  'karaikudi-to-kanyakumari',
  'karaikudi-to-villupuram',
  'karaikudi-to-karur',
  'karaikudi-to-dharmapuri',
  'karaikudi-to-krishnagiri',
  'karaikudi-to-pollachi',
  'karaikudi-to-palani',
  'karaikudi-to-kodaikanal',
  'karaikudi-to-tiruvannamalai',
  'karaikudi-to-cuddalore',
  'karaikudi-to-marthandam',
  'karaikudi-to-tenkasi',
  'karaikudi-to-attur',
  'vellore-to-chennai',
  'vellore-to-madurai',
  'vellore-to-coimbatore',
  'vellore-to-salem',
  'vellore-to-tirunelveli',
  'vellore-to-erode',
  'vellore-to-thanjavur',
  'vellore-to-kumbakonam',
  'vellore-to-nagercoil',
  'vellore-to-dindigul',
  'vellore-to-karaikudi',
  'vellore-to-tiruppur',
  'vellore-to-hosur',
  'vellore-to-puducherry',
  'vellore-to-kanyakumari',
  'vellore-to-namakkal',
  'vellore-to-dharmapuri',
  'vellore-to-krishnagiri',
  'vellore-to-palani',
  'vellore-to-ooty',
  'vellore-to-tiruvannamalai',
  'vellore-to-cuddalore',
  'vellore-to-marthandam',
  'vellore-to-tenkasi',
  'vellore-to-rasipuram',
  'tiruppur-to-chennai',
  'tiruppur-to-madurai',
  'tiruppur-to-coimbatore',
  'tiruppur-to-salem',
  'tiruppur-to-tirunelveli',
  'tiruppur-to-erode',
  'tiruppur-to-thanjavur',
  'tiruppur-to-kumbakonam',
  'tiruppur-to-nagercoil',
  'tiruppur-to-karaikudi',
  'tiruppur-to-vellore',
  'tiruppur-to-hosur',
  'tiruppur-to-puducherry',
  'tiruppur-to-kanyakumari',
  'tiruppur-to-villupuram',
  'tiruppur-to-karur',
  'tiruppur-to-namakkal',
  'tiruppur-to-dharmapuri',
  'tiruppur-to-krishnagiri',
  // Tiruchirappalli (Trichy) — major hub, high search volume
  'tiruchirappalli-to-chennai',
  'tiruchirappalli-to-coimbatore',
  'tiruchirappalli-to-tirunelveli',
  'tiruchirappalli-to-bangalore',
  'tiruchirappalli-to-thanjavur',
  'tiruchirappalli-to-kumbakonam',
  'tiruchirappalli-to-dindigul',
  'tiruchirappalli-to-hosur',
  'tiruchirappalli-to-kanyakumari',
  'tiruchirappalli-to-villupuram',
  'tiruchirappalli-to-namakkal',
  'tiruchirappalli-to-dharmapuri',
  'tiruchirappalli-to-krishnagiri',
  'tiruchirappalli-to-ooty',

  // Thoothukudi (Tuticorin)
  'thoothukudi-to-chennai',
  'thoothukudi-to-madurai',
  'thoothukudi-to-coimbatore',
  'thoothukudi-to-tirunelveli',
  'thoothukudi-to-nagercoil',
  'thoothukudi-to-kanyakumari',
  'thoothukudi-to-dindigul',
  // Theni
  'theni-to-chennai',
  'theni-to-madurai',
  'theni-to-coimbatore',
  'theni-to-tirunelveli',
  'theni-to-dindigul',
  'theni-to-kanyakumari',
  'theni-to-kumbakonam',
  // Virudhunagar
  'virudhunagar-to-madurai',
  'virudhunagar-to-tirunelveli',
  'virudhunagar-to-coimbatore',
  'virudhunagar-to-nagercoil',
  // Nagapattinam
  'nagapattinam-to-chennai',
  'nagapattinam-to-madurai',
  'nagapattinam-to-kumbakonam',
  'nagapattinam-to-thanjavur',
  // Mayiladuthurai
  'mayiladuthurai-to-chennai',
  'mayiladuthurai-to-madurai',
  'mayiladuthurai-to-kumbakonam',
  'mayiladuthurai-to-thanjavur',
  // Sivaganga
  'sivaganga-to-chennai',
  'sivaganga-to-madurai',
  'sivaganga-to-karaikudi',
  // Rajapalayam — major southern hub, high GSC click signal
  'rajapalayam-to-sankarankovil',
  'rajapalayam-to-kovilpatti',
  'rajapalayam-to-tenkasi',
  'rajapalayam-to-virudhunagar',
  'rajapalayam-to-aruppukkottai',
  'rajapalayam-to-tiruppur',
  'rajapalayam-to-papanasam',
  'rajapalayam-to-chennai',
  'rajapalayam-to-palani',
  'rajapalayam-to-coimbatore',
  // Virudhunagar — expanded beyond existing 5 slugs
  'virudhunagar-to-aruppukkottai',
  'virudhunagar-to-tirumangalam',
  'virudhunagar-to-rajapalayam',
  'virudhunagar-to-sivakasi',
  // Kanchipuram — district capital, north TN
  'kanchipuram-to-vellore',
  'kanchipuram-to-tiruvannamalai',
  'kanchipuram-to-bangalore',
  'kanchipuram-to-tindivanam',
  'kanchipuram-to-viluppuram',
  // Gobichettipalayam — Erode district hub
  'gobichettipalayam-to-coimbatore',
  'gobichettipalayam-to-tiruppur',
  'gobichettipalayam-to-mettupalayam',
  // Batlagundu — Dindigul district junction
  'batlagundu-to-tiruppur',
  'batlagundu-to-kodaikanal',
  'batlagundu-to-palani',
  'batlagundu-to-coimbatore',
  // Chidambaram — Cuddalore district
  'chidambaram-to-chennai',
  // Cumbum — Theni district
  'cumbum-to-tiruppur',
  'cumbum-to-coimbatore',
  // Edappadi — Salem district
  'edappadi-to-kumarapalayam',
  'edappadi-to-bhavani',
  // Thanjavur — expanded delta region routes
  'thanjavur-to-pattukkottai',
  'thanjavur-to-pudukkottai',
  'thanjavur-to-ariyalur',
  'thanjavur-to-mannargudi',
  'thanjavur-to-velankanni',
  'thanjavur-to-tiruvarur',
  'thanjavur-to-papanasam',
  // Tirunelveli — expanded southern routes
  'tirunelveli-to-sathankulam',
  'tirunelveli-to-aruppukkottai',
  'tirunelveli-to-vilathikulam',
  // Dindigul — expanded beyond existing slugs
  'dindigul-to-pudukkottai',
  'dindigul-to-ponnamaravathi',
  'dindigul-to-cumbum',
  'dindigul-to-sivagangai',
  'dindigul-to-kumily',
] as const;

// Unique origin cities extracted from inter-city + city bus slugs.
// Used by /buses-from/[city] hub pages and sitemap.
export function getHubCities(): string[] {
  const cities = new Set<string>();
  for (const slug of SEO_ROUTE_SLUGS) {
    const from = slug.split('-to-')[0];
    if (from) cities.add(from);
  }
  for (const slug of CITY_BUS_ROUTE_SLUGS) {
    const from = slug.split('-to-')[0];
    if (from) cities.add(from);
  }
  return [...cities].sort();
}

// Get all destination slugs reachable from a given origin city.
export function getRoutesFromCity(citySlug: string): {
  interCity: { toSlug: string; routeSlug: string }[];
  cityBus: { toSlug: string; routeSlug: string }[];
} {
  const interCity = SEO_ROUTE_SLUGS
    .filter((slug) => slug.startsWith(`${citySlug}-to-`))
    .map((slug) => ({ toSlug: slug.split('-to-')[1] ?? '', routeSlug: slug }))
    .filter((r) => r.toSlug.length > 0);
  const cityBus = CITY_BUS_ROUTE_SLUGS
    .filter((slug) => slug.startsWith(`${citySlug}-to-`))
    .map((slug) => ({ toSlug: slug.split('-to-')[1] ?? '', routeSlug: slug }))
    .filter((r) => r.toSlug.length > 0);
  return { interCity, cityBus };
}

// Chennai city bus (MTC) route slugs
export const CITY_BUS_ROUTE_SLUGS = [
  // Chennai MTC
  'kilambakkam-to-koyambedu',
  'kilambakkam-to-thiruvanmiyur',
  'koyambedu-to-avadi',
  'avadi-to-koyambedu',
  'poonamallee-to-koyambedu',
  'poonamallee-to-royapuram',
  'royapuram-to-poonamallee',
  'avadi-to-poonamallee',
  'poonamallee-to-avadi',
  'poonamallee-to-sunguvarchathiram',
  'sunguvarchathiram-to-poonamallee',
  'vadapalani-to-koyambedu',
  'koyambedu-to-vadapalani',
  'tambaram-to-kilambakkam',
  'kilambakkam-to-tambaram',
  'royapuram-to-iyyappanthangal',
  'kilambakkam-to-avadi',
  'avadi-to-kilambakkam',
  'koyambedu-to-royapuram',
  'royapuram-to-koyambedu',
  'royapuram-to-tambaram',
  'tambaram-to-royapuram',
  'royapuram-to-kundrathur',
  'kundrathur-to-royapuram',
  'tambaram-to-koyambedu',
  // Madurai city bus (maduraiguide.in data)
  // From Periyar Bus Stand (central depot)
  'periyar-bus-stand-to-arappalayam',
  'arappalayam-to-periyar-bus-stand',
  'periyar-bus-stand-to-thirumangalam',
  'periyar-bus-stand-to-usilampatti',
  'periyar-bus-stand-to-melur',
  'melur-to-periyar-bus-stand',
  'periyar-bus-stand-to-simmakkal',
  'simmakkal-to-periyar-bus-stand',
  'periyar-bus-stand-to-alagarkovil',
  'periyar-bus-stand-to-sholavandan',
  'periyar-bus-stand-to-vadipatti',
  'periyar-bus-stand-to-alanganallur',
  'periyar-bus-stand-to-palamedu',
  'periyar-bus-stand-to-airport',
  'periyar-bus-stand-to-vandiyur',
  'periyar-bus-stand-to-thiruppalai',
  'thiruppalai-to-periyar-bus-stand',
  // From Arappalayam
  'arappalayam-to-thirumangalam',
  'arappalayam-to-simmakkal',
  'simmakkal-to-arappalayam',
  'arappalayam-to-alagarkovil',
  'arappalayam-to-melur',
  'melur-to-arappalayam',
  // From MGR Bus Stand (Mattuthavani)
  'mgr-bus-stand-to-airport',
  'mgr-bus-stand-to-periyar-bus-stand',
  'periyar-bus-stand-to-mgr-bus-stand',
] as const;

// Via-stop slugs — intermediate towns that buses pass through.
// Powers /via/[stop] pages — blue ocean SEO, no competitor has these.
// Only include stops verified to have intermediate stop_times data in the DB.
// More stops will be added as TNSTC scraper data (Phase 3) populates stop_times.
export const VIA_STOP_SLUGS = [
  // High count (30+ buses) — best SEO value
  'palani',
  'ooty',
  'madurai',
  'coimbatore',
  'avinashi',
  'ramanathapuram',
  'tirumangalam',
  'melur',
  'sholavandan',
  'kovilpatti',
  // Medium count (5–29 buses)
  'karur',
  'usilampatti',
  'perundurai',
  'sankagiri',
  'dindigul',
  'namakkal',
  'shenkottai',
  // Lower count (1–4 buses) — kept as they'll grow with more data
  'mettupalayam',
  'udumalpet',
  'natham',
  'dharapuram',
  'sathyamangalam',
  // Added Apr 28 — already indexed via dynamic fallback, now in sitemap
  'batlagundu',
  'chidambaram',
  // New stops from tickettogetlost data — all validated against production API
  'oddanchatram',
  'viluppuram',
  'kanchipuram',
  'chengalpattu',
  'sankarankovil',
  'edappadi',
  'thiruppattur',
  'cumbum',
  'panruti',
  'gobichettipalayam',
  'sholingur',
  'vellakovil',
  'vaniyambadi',
  'kalaiyar-kovil',
] as const;
