#!/usr/bin/env tsx
/**
 * verify-candidates.ts
 *
 * Reads seo-candidates.json (generated by backend/scripts/discover-seo-candidates.ts)
 * and checks each candidate slug against the production search API.
 * Slugs returning ≥3 results are written to seo-verified.json; others to seo-failed.json.
 * Already-verified slugs in SEO_ROUTE_SLUGS are skipped automatically.
 *
 * Usage:
 *   npx tsx scripts/verify-candidates.ts               # all candidates
 *   npx tsx scripts/verify-candidates.ts --tier T1xT1  # one tier only (run first)
 *   npx tsx scripts/verify-candidates.ts --from-index 200  # resume run
 *   npx tsx scripts/verify-candidates.ts --limit 100   # cap batch size
 *
 * Output files (appended across runs):
 *   ../backend/data/processed/seo-verified.json
 *   ../backend/data/processed/seo-failed.json
 */

import fs from 'fs/promises';
import path from 'path';
import { SEO_ROUTE_SLUGS } from '../app/lib/seo-routes.ts';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const BACKEND_DATA = path.join(ROOT, '..', 'backend', 'data', 'processed');
const CANDIDATES_FILE = path.join(BACKEND_DATA, 'seo-candidates.json');
const VERIFIED_FILE = path.join(BACKEND_DATA, 'seo-verified.json');
const FAILED_FILE = path.join(BACKEND_DATA, 'seo-failed.json');

const API_BASE =
  process.env.CHECK_API_BASE_URL ??
  process.env.NEXT_PUBLIC_SEARCH_API_BASE_URL ??
  'https://hopivdsbzzfklohyllut.supabase.co/functions/v1/api';

const CONCURRENCY = 5;
const DELAY_MS = 300;

type Candidate = {
  from: string;
  to: string;
  slug: string;
  tier: string;
  fromCount?: number;
  toCount?: number;
  fromType?: string;
  toType?: string;
};

type VerifiedEntry = Candidate & { resultCount: number };

function slugToQuery(slug: string): string {
  return slug.replace(/-+/g, ' ').trim();
}

async function checkSlug(candidate: Candidate): Promise<number> {
  const params = new URLSearchParams({
    from: slugToQuery(candidate.from),
    to: slugToQuery(candidate.to),
    type: 'inter-city',
  });

  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const res = await fetch(`${API_BASE}/search?${params}`, {
        signal: AbortSignal.timeout(15_000),
      });
      if (!res.ok) {
        if (attempt === 0) await delay(2_000);
        continue;
      }
      const data = (await res.json()) as { count?: number; results?: unknown[] };
      return data.count ?? data.results?.length ?? 0;
    } catch {
      if (attempt === 0) await delay(2_000);
    }
  }
  return 0;
}

function delay(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

async function runWithConcurrency<T>(
  items: T[],
  concurrency: number,
  fn: (item: T) => Promise<void>,
): Promise<void> {
  const queue = [...items];
  await Promise.all(
    Array.from({ length: Math.min(concurrency, items.length) }, async () => {
      while (queue.length > 0) {
        await fn(queue.shift()!);
        if (DELAY_MS > 0) await delay(DELAY_MS);
      }
    }),
  );
}

function formatTypescript(verified: VerifiedEntry[]): string {
  const byTier = new Map<string, VerifiedEntry[]>();
  for (const v of verified) {
    const list = byTier.get(v.tier) ?? [];
    list.push(v);
    byTier.set(v.tier, list);
  }

  const lines: string[] = ['// ─── Paste into SEO_ROUTE_SLUGS in app/lib/seo-routes.ts ───'];
  for (const [tier, entries] of byTier) {
    lines.push(`  // ${tier} — ${entries.length} new routes`);
    for (const e of entries) {
      lines.push(`  '${e.slug}',`);
    }
  }
  return lines.join('\n');
}

async function loadJson<T>(file: string): Promise<T[]> {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8')) as T[];
  } catch {
    return [];
  }
}

async function main() {
  const args = process.argv.slice(2);
  const getArg = (flag: string) => args[args.indexOf(flag) + 1];

  const fromIndex = parseInt(getArg('--from-index') ?? '0', 10) || 0;
  const limitArg = parseInt(getArg('--limit') ?? '0', 10);
  const tierFilter = getArg('--tier') ?? null;

  const alreadyVerified = new Set(SEO_ROUTE_SLUGS as readonly string[]);

  const allCandidates = await loadJson<Candidate>(CANDIDATES_FILE);
  if (allCandidates.length === 0) {
    console.error(`No candidates found at ${CANDIDATES_FILE}`);
    console.error('Run: cd ../backend && DATABASE_URL=... npx tsx scripts/discover-seo-candidates.ts');
    process.exit(1);
  }

  let candidates = allCandidates.slice(fromIndex).filter((c) => !alreadyVerified.has(c.slug));
  if (tierFilter) candidates = candidates.filter((c) => c.tier === tierFilter);
  if (limitArg > 0) candidates = candidates.slice(0, limitArg);

  const existingVerified = await loadJson<VerifiedEntry>(VERIFIED_FILE);
  const existingFailed = await loadJson<VerifiedEntry>(FAILED_FILE);
  const doneSet = new Set([
    ...existingVerified.map((e) => e.slug),
    ...existingFailed.map((e) => e.slug),
  ]);

  const toCheck = candidates.filter((c) => !doneSet.has(c.slug));
  const skipped = allCandidates.length - candidates.length - fromIndex;

  console.log(`Candidates: ${allCandidates.length} total | skipping ${skipped} (already verified or before --from-index)`);
  console.log(`To check: ${toCheck.length} | already done in prior runs: ${candidates.length - toCheck.length}`);
  console.log(`API: ${API_BASE}\n`);

  const newVerified: VerifiedEntry[] = [];
  const newFailed: VerifiedEntry[] = [];
  let checked = 0;

  await runWithConcurrency(toCheck, CONCURRENCY, async (candidate) => {
    const count = await checkSlug(candidate);
    checked++;
    const entry: VerifiedEntry = { ...candidate, resultCount: count };

    if (count >= 3) {
      newVerified.push(entry);
      process.stdout.write(`  [${checked}/${toCheck.length}] PASS (${count}): ${candidate.slug}\n`);
    } else {
      newFailed.push(entry);
      process.stdout.write(`  [${checked}/${toCheck.length}] fail (${count}): ${candidate.slug}\r`);
    }
  });

  await fs.writeFile(VERIFIED_FILE, JSON.stringify([...existingVerified, ...newVerified], null, 2));
  await fs.writeFile(FAILED_FILE, JSON.stringify([...existingFailed, ...newFailed], null, 2));

  const totalVerified = existingVerified.length + newVerified.length;

  console.log(`\n\n─── Run complete ───`);
  console.log(`Checked: ${checked}  |  Passed: ${newVerified.length}  |  Failed: ${newFailed.length}`);
  console.log(`Total verified across all runs: ${totalVerified}`);

  if (newVerified.length > 0) {
    console.log('\n─── Paste into app/lib/seo-routes.ts ───\n');
    console.log(formatTypescript(newVerified));
    console.log('\n─── Then run: npm run check:routes && git push ───');
  }
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
